config/routes.rb
Rails.application.routes.draw do

  post 'add_to_cart' => 'cart#add_to_cart'

  # delete 'remove_from_cart' => 'cart#remove_from_cart'

  get 'view_order' => 'cart#view_order'
  
  get 'checkout' => 'cart#checkout'

  devise_for :users

  root 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.admin?
        can :manage, Product
    elsif user.guest?
        can :show, Product
        
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/line_item.rb
class LineItem < ApplicationRecord

	belongs_to :product
	belongs_to :order, optional: true
	
end

app/models/order.rb
class Order < ApplicationRecord

	belongs_to :user, optional: true
	has_many :line_items

	serialize :order_items, Hash
end

app/models/product.rb
class Product < ApplicationRecord
	
	mount_uploader :image, ImageUploader
	belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

  def admin?
  	role == "admin"
  end

  def guest?
  	role == "guest"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :categories, :brands
before_action :configure_permitted_parameters, if: :devise_controller?

	def categories
		@categories = Category.order(:name)
	end

	def brands
		@brands = Product.pluck(:brand).sort.uniq
		
	end

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
		devise_parameter_sanitizer.permit(:account_update, keys: [:role])
	end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_action :authenticate_user!, except: [:add_to_cart, :view_order]

  def add_to_cart
    check = LineItem.find_by(product_id: params[:product_id])
    if check
      check.update(quantity: (check.quantity + params[:quantity].to_i))
      check.update(line_item_total: (check.quantity * check.product.price))
    else
      line_item = LineItem.create(product_id: params[:product_id], quantity: params[:quantity])
      line_item.update(line_item_total: (line_item.quantity * line_item.product.price))
    end
    redirect_back(fallback_location: root_path)
  end

  def view_order
  	@line_items = LineItem.all
  end

  # def remove_from_cart(item_id)
  #   line_item = LineItem.find(item_id).destroy
  #   redirect_back(fallback_location: root_path)
  # end

  def checkout
    line_items = LineItem.all

    @order = Order.create(user_id: current_user.id, subtotal: 0)

    line_items.each do |l_item|
      l_item.product.update(quantity: (l_item.product.quantity - l_item.quantity))
      @order.order_items[l_item.product_id] = l_item.quantity
      @order.subtotal += l_item.line_item_total
    end
      @order.save

      @order.update(sales_tax: (@order.subtotal * 0.08))
      @order.update(grand_total: (@order.sales_tax + @order.subtotal))

      line_items.destroy_all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :category_id, :image, :brand)
    end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_items
  	@products = Product.all
  end

  def items_by_category
  	@products = Product.where(category: params[:category_id])
  	@category = Category.find(params[:category_id])
  end

  def items_by_brand
	@products = Product.where(brand: params[:brand])
	@brand = params[:brand]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h2>Thank you for buying our stuff!</h2>

<p>Let's review your order:</p>

<% @order.order_items.each do |k, v| %>
	<ul>
		<li><%= Product.find(k).name %>, qty: <%= v %> </li>
	</ul>
<% end %>

<p>
	<strong> Order Total: <%= number_to_currency @order.grand_total %> </strong>
</p>

app/views/cart/view_order.html.erb
<h1>Your Cart</h1>

<div>
	<% if @line_items != nil %>
		
		<div class="row">
			<div class="card-deck">
			  <% @line_items.each do |item| %>
			    <div class="col-md-2 d-flex align-items-stretch">
			      <div class="card mb-2">

			        <div class="card-body">
			          <% if item.product.image.url.nil? == false %>
			            <p><%= image_tag item.product.image.url %></p>
			          <% end %>


			        </div>

				    <div class="card-footer">
			          <h6><%= link_to item.product.name, item.product, class: "card-title" %></h6>
			          <p><%= number_to_currency item.product.price %></p>
			          <p>Qty: <%= item.quantity %></p>
			          <p>Subtotal: <%= number_to_currency item.line_item_total %></p>





			        </div>

			      </div>
			    </div>
			  <% end %>
			</div>
		</div>
	 	<div>
	 		
	 	</div>
	<% else %>

		<p>Your cart is empty.</p>
		<p><%= link_to "Shop", root_path, class: "btn btn-success" %></p>

	<% end %>

</div>
<div>
	<%= link_to "Proceed to Checkout", checkout_path, class: "btn btn-success" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <h1><%= link_to "EShop", root_path, class: "navbar-link" %></h1><span class="sr-only">(current)</span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown">Shop by Category</a>

              <div class="dropdown-menu">
                <% @categories.each do |category| %>

                  <%= link_to category.name, categorical_path(category_id: category.id), class: "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                <% end %>
                <%= link_to 'All', root_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
            </li>  
          </ul>

          <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Shop by Brand
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% @brands.each do |brand| %>
                <%= link_to brand, branding_path(brand: brand), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>              
              <% end %>
              <%= link_to 'All', root_path, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>


      <div class="navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown"> 
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.email %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div> 
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          </ul> 
          <% else %>
          <ul class="navbar-nav">
              <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
              </li>
          </ul>
          <% end %>
          <ul class="navbar-nav">
            <li><%= link_to "View Cart", view_order_path, class: "fa fa-shopping-cart fa-2x" %> </li>
      </div>
    </nav>

<!--     <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
        <%= link_to "Home", root_path, class: "navbar-link" %><span class="sr-only">(current)</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown">Shop by Category</a>

              <div class="dropdown-menu">
                <% @categories.each do |category| %>

                  <%= link_to category.name, categorical_path(category_id: category.id), class: "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                <% end %>
                <%= link_to 'All', root_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
            </li>  
          </ul>

          <ul class="navbar-nav float-right">
              <li class="nav-item dropdown"><span class="caret"></span>
                  <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                  </div>
              </li>
          </ul>
    </nav> -->


    <div class="container">
      <%= yield %>
    </div>


  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.select :category_id, @categories.collect { |c| [c.name, c.id] }, {include_blank: "Please select a category"}, class: "form-control" %>
  </div>

  <div class="custom-file">
    <%= form.label :image, class: "custom-file-label" %>
    <%= form.file_field :image, class: "custom-file-input" %>    
  </div>

  <%= form.file_field :image %>

  <div>
    <%= form.submit %>
  </div>
 <!--  <%= button_to "Submit", action: :create, controller: :products, class: "btn btn-success" %> -->
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <!-- <th>Rating</th> -->
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>


        <td><%= product.category_id %></td>
        <td><%= link_to 'Show', product %></td>
        <% if can? :update, Product%>        
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Product %>
  <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/storefront/_product_loop.html.erb
<div class="row">
	<div class="card-deck">
	  <% @products.each do |item| %>
	  	<% if item.quantity > 0 %>
		    <div class="col-md-4 d-flex align-items-stretch">
		      <div class="card mb-4">

		        <div class="card-body">
		          <% if item.image.url.nil? == false %>
		            <p><%= image_tag item.image.url %></p>
		          <% end %>
		        </div>

			    <div class="card-footer">
		          <h4><a href="#" data-toggle="modal" data-target="#modal_<%= item.id %>"><%= item.name %></a></h4>
		          <p><%= number_to_currency item.price %></p>
		          <p><a href="#" data-toggle="modal" data-target="#modal_<%= item.id %>"><span class="fa fa-plus"></span>Quick Info</a></p>
		        </div>

		      </div>
		    </div>

<!-- modal	     -->
		    <div class="modal fade" id="modal_<%= item.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		      <div class="modal-dialog" role="document">
		        <div class="modal-content">
		          <div class="modal-header">
		            <h5 class="modal-title" id="exampleModalLabel"><%= item.name %></h5>
		            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		              <span aria-hidden="true">&times;</span>
		            </button>
		          </div>
		          <div class="modal-body">
		            <div class="card">
		              
		              <div class="card-im-top">
		                <% if item.image.url.nil? == false %>
		                  <p><%= image_tag item.image.url, width: "100%" %></p>
		                <% end %>
		              </div>

		              <div class="card-body">
		                <h4><%= item.name %></h4>
		                <p><%= number_to_currency item.price %></p>
		                <p><%= item.description %></p>
		              </div>

		            </div>
		          </div>
		          <div class="modal-footer">
		            <p>
		            	<%= form_with(url: add_to_cart_path) do |form| %>
		            		<%= form.hidden_field :product_id, value: item.id %>
		            		<%= form.number_field :quantity, value: 1 %>
		            		<%= form.submit "Add to Cart", class: "btn btn-success" %>
		            	<% end %>
		            </p>
		          </div>
		        </div>
		      </div>
		    </div>
		<% end %>
	  <% end %>
	</div>
</div>

app/views/storefront/all_items.html.erb
<h1>All Items</h1>

<%= render 'product_loop' %>

app/views/storefront/items_by_brand.html.erb
<h1>All <%= @brand %> Products</h1>

<%= render 'product_loop' %>

app/views/storefront/items_by_category.html.erb
<h1>All <%= @category.name %></h1>

<%= render 'product_loop' %>